### ISSUE TITLE
Java SDK

### ISSUE THREAD

**Issue by ajschwieterman** [goabstract/abstract-sdk#128]
It would be cool to download a Java SDK of the Abstract SDK that can make these HTTPS calls to any Abstract information you're looking for.  The CLI environment is nice to find layers and files locally, but i would like to accessing my Abstract information when my program is being executed on an AWS remote server.

For example, Amazon Web Services provide and CLI interface and a **Java SDK library** to access my AWS information.

Not sure if this is in the plan for the Abstract team, but I think this feature would be handy.

**Comment by bitpshr** [comment]
Hi @ajschwieterman, thanks for reaching out. While we may consider it in the future, we don't currently have any plans to expose a Java SDK alongside this JavaScript SDK. We do eventually plan to open up our underlying HTTP API; this would allow Java (or any other type of) programs to remotely access Abstract data by making HTTP requests directly without any SDK.

It should be noted that this JavaScript SDK can be used in remote environments since it exposes an [API transport](https://sdk.goabstract.com/docs/transports/#api) that makes HTTPS calls. If Java is not a hard requirement for your use case, it's possible to use the SDK on any remote server that supports JavaScript, including AWS.

Thanks again for putting Java integration on our radar. Don't hesitate to let us know if you have any additional questions or issues trying out the SDK on a remote server.

**Comment by ajschwieterman** [comment]
Excellent.  Thanks for replying back about this.  Let me know when the underlying HTTP API gets opened up.

**Comment by bitpshr** [comment]
@ajschwieterman: Until the HTTP API is made public (which probably won't be for some time), it's always possible to check what the JavaScript SDK does under the hood and then to implement that same logic in Java. I know it's not ideal and would require effort, but it boils down to:

1. [Making HTTP requests with correct headers](https://github.com/goabstract/abstract-sdk/blob/master/src/endpoints/Endpoint.js#L180-L231)
1. Parsing responses (usually JSON)

This is definitely possible to do from a Java environment now if desired and motivated and we'd be happy to offer guidance along the way.

Closing this issue for now since the original question was answered, but never hesitate to open up new issues if you have additional questions or ideas.

**Comment by austin94** [comment]
Has there been any update on the timeline for a publicly consumable HTTP API?
