### ISSUE TITLE
Retrieve a file endpoint can be called without setting access token.

### ISSUE THREAD

**Issue by narusevic** [goabstract/abstract-sdk#188]
Called https://sdk.goabstract.com/docs/abstract-api/#retrieve-a-file method with projectId, branchId, fileId, sha: "latest" without access token and got the file. It should not be like that. Did not check other methods, but got Unauthorized error while calling https://sdk.goabstract.com/docs/abstract-api/#list-all-projects.

**Comment by tommoor** [comment]
Hi @narusevic could you confirm the transport In use? A token is not required for the majority of the CLI operations as the data is loaded from your local disk

**Comment by bitpshr** [comment]
Hi @narusevic, thanks for taking the time to file this issue. Like @tommoor mentioned, a token is only required when using the API transport. This means that retrieving a file via the CLI transport will work without any authentication credentials since the SDK is using data that's already stored locally on your computer. You can find more information on transports [here](https://developer.abstract.com/docs/transports/).

If the the CLI transport is being used for `client.files.info({ ... })` and if the API transport is being used for `client.projects.info({ ... })`, then the behavior you described is expected. Could you confirm the transports being used?

Thanks in advance!

**Comment by bitpshr** [comment]
Don't hesitate to reopen this issue or to open a new one if you're still having issues.
