### ISSUE TITLE
CLI Path defaulting to relative project path

### ISSUE THREAD

**Issue by MichaelZaporozhets** [goabstract/abstract-sdk#196]
I presume this must be a webpack issue, but my application now looks for abstract-cli in my project directory/dist/bin and obviously error's out when it doesn't find it there.

currently added a symlink to my build task that that looks like this: 

```
"build": "rm -rf dist && webpack && mkdir dist/bin && ln -s $(pwd)/node_modules/@elasticprojects/abstract-cli/bin/abstract-cli $(pwd)/dist/bin/abstract-cli",
```

**Comment by bitpshr** [comment]
Hi @MichaelZaporozhets, thanks for reaching out. The SDK previously did a dynamic `require` for `@elasticprojects/abstract-cli` when calling a method on the CLI transport. It's possible that this inline `require` statement caused downstream application builds to fail when dynamically finding `@elasticprojects/abstract-cli` at runtime. This has been fixed so that the CLI is treated like any other Node-specific dependency, and can be tested using the latest `abstract-sdk@8.0.0-beta.7` prerelease.

Don't hesitate to reopen this issue or to file a new one if you still have issues.

**Comment by MichaelZaporozhets** [comment]
@bitpshr I'm experiencing this issue again, when bundling my application:

`Error: abstract-cli could not be accessed at the expected path: /Users/me/path/to/project/projectname/dist/bin/abstract-cli`

the post-install symlink solution works, but very ugly.

**Comment by igorsheg-wix** [comment]
Any news regrading this issue?
I'm eperincing the same thing with `abstract-sdk@8.0.0-beta.14`

**Comment by MichaelZaporozhets** [comment]
@igorsheg-wix feel free to use this fix (here's how I ensure my package ends up working using package.json lifecycle hooks): 
```json
{
    "fixACLIPath": "mkdir dist/bin && ln -s $(pwd)/node_modules/@elasticprojects/abstract-cli/bin/abstract-cli $(pwd)/dist/bin/abstract-cli",
    "install": "npm run fixACLIPath"
}
