### ISSUE TITLE
`assets.file` endpoint ignoring `sha` filter option

### ISSUE THREAD

**Issue by austin94** [goabstract/abstract-sdk#230]
I'm attempting to use the [`assets.file()`](https://sdk.goabstract.com/docs/abstract-api/#list-assets-for-a-file) method to list all assets of a file at a specific `sha` ("latest" normally).

It appears that the `sha` filter option used in the `FileDescriptor` is being ignored.

Running the following:

```
abstract.assets.file({
  projectId: "PROJECT_ID",
  branchId: "master",
  fileId: "FILE_ID,
  sha: "SPECIFIC_SHA"
}
```

returns the assets of the specified SHA, but also returns all previously generated assets.

Is this expected?

**Comment by berezovskycom** [comment]
Hi @austin94!
Thanks for filing an issue, it does not look like an expected behavior.
I tested on SDK how url changes and different sha's provide different links.
I'll file an issue and let our back end devs have a look from server side.
Please excuse us for a bit of answer delay, we've been working on something that definitely would interest you.
Feel free to share more SDK things with us!  🙌

**Comment by berezovskycom** [comment]
Hi @austin94! SHA gets used only in `cli`

**Comment by austin94** [comment]
Interesting. Is there a way to denote that in the documentation? [list assets for a file](https://sdk.goabstract.com/docs/abstract-api/#list-assets-for-a-file) includes the `API` tag.

It looks like only `latest` assets are now being returned by the endpoint so you can mark this as closed as that fixed the issue for us.
